/*
 * This class was automatically generated by the ${product_name} version ${product_version}.
 * For more information please refer to the ${product_url}.
 */
${package_decl}

${import_decls}

public class ${parser_type} extends Parser<${result_type}> {
    
    // Interface
    
    @Override
    protected final Grammar getGrammar() {
        return GRAMMAR;
    }
    
    @Override
    protected Transaction getTransaction() {
        // FIXME
        return Transaction.STATELESS;
    }
    
    @Override
    protected ${result_type} buildResult() {
        // TODO
        return null;
    }
    
    // Actions
    
    ${action_methods}
    // Grammar
    
    private static final Grammar GRAMMAR = new GrammarBuilder()
            ${grammar_statements}
            
            .buildGrammar();
    
}

${problems}